# Generated by Django 5.2.3 on 2025-06-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienvenida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='apellido',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mascota',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='breed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='species',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='bienvenida.owner'),
            preserve_default=False,
        ),
    ]
